# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2021-12-25T13:38:23+00:00

from __future__ import annotations

from pydantic import Field, RootModel

from asyncio_red.events import BaseEvent


class Service1Schema(RootModel):
    pass


class EventViaList(BaseEvent):
    """
    @DynamicAttrs
    """

    value: str = Field(..., title='Value')


class EventViaChannel(BaseEvent):
    """
    @DynamicAttrs
    """

    value: str = Field(..., title='Value')


class EventViaStream(BaseEvent):
    """
    @DynamicAttrs
    """

    value: str = Field(..., title='Value')
