# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2021-12-25T13:38:23+00:00

from __future__ import annotations

from typing import Any

from asyncio_red.events import BaseEvent
from pydantic import Field


class Service1Schema(BaseEvent):
    __root__: Any = Field(..., title='service_1 schema')


class EventViaList(BaseEvent):
    """
    @DynamicAttrs
    """

    value: str = Field(..., title='Value')


class EventViaChannel(BaseEvent):
    """
    @DynamicAttrs
    """

    value: str = Field(..., title='Value')


class EventViaStream(BaseEvent):
    """
    @DynamicAttrs
    """

    value: str = Field(..., title='Value')
